--- #YAML:1.0
name:                Mindcal
version:             0.01
abstract:            Calculate day-of-week of any given date in your head
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    DateTime:                      0.38
    Log::Log4perl:                 1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike Schilli <m@perlmeister.com>
